### PR TITLE
Add AlmaLinux 9

### PR DESCRIPTION
**Pull request by ArtofBugs**
- Support AlmaLinux 9
- In the default integration test, catch the deprecated `version` parameter warning from the upstream docker-compose files

### CODE REVIEW

**Comment by ramereth** [comment]
@ArtofBugs so the integration test is still failing:
```
     ×  Command: `/usr/local/libexec/mattermost-backup.sh` stderr is expected to eq ""
     
     expected: ""
          got: "time=\"2024-10-22T21:34:35Z\" level=warning msg=\"/var/lib/mattermost/docker-compose.yml: the attrib...
ribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion\"\n"
     
     (compared using ==)
```
This file isn't managed by Chef and comes from the upstream repository. We may want to update the check to ignore any lines that complain about the version deprecation.

**Comment by ArtofBugs** [comment]
Ah ok, makes sense - will do :+1:

**Comment by ArtofBugs** [comment]
Done, all tests passing!

**Review by ramereth — APPROVED** [review]
Patch bump

**Comment by ArtofBugs** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `main` and has automatically performed a patch-level version bump to v1.1.4.  Have a nice day!

**Pull request merged**
